version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: quay.io/wakaba/docker-perl-app-base
    steps:
      - run: cd /app && perl local/bin/pmbp.pl --update-pmbp-pl
      - run: cd /app && perl local/bin/pmbp.pl --install-commands "git tar"
      - run: apt-get install -y ssh ca-certificates gzip

      - checkout

      - run:
          command: docker pull quay.io/wakaba/chromedriver:stable
          no_output_timeout: 600s
          background: true

      - restore_cache:
          keys:
            - deps-{{ .Branch }}
      - run:
          command: bash .circleci/test-deps
          no_output_timeout: 600s
      - save_cache:
          key: deps-{{ .Branch }}
          paths:
            - local/perlbrew/perls
            - deps/pmtar

      - run: git config --global user.email "temp@circleci.test"
      - run: git config --global user.name "CircleCI"
      
      - run:
          command: make test-local-http-circle
          no_output_timeout: 600s
      - run:
          command: WEBUA_DEBUG=1 TEST_WEBDRIVER_BROWSERS="chrome" make test-local-web-circle
          no_output_timeout: 600s
