version: 2
jobs:
  build:
    working_directory: /repo
    docker:
      - image: quay.io/wakaba/docker-perl-app-base
    steps:
      - run:
          command: perl local/bin/pmbp.pl --update-pmbp-pl
          working_directory: /app
      - run:
          command: perl local/bin/pmbp.pl --install-commands "git tar"
          working_directory: /app
      - run: apt-get install -y ssh ca-certificates gzip

      - checkout
      - run: mv /repo/* /repo/.* /app

      - restore_cache:
          keys:
            - deps-{{ .Branch }}
      - run:
          command: bash .circleci/test-deps
          working_directory: /app
          no_output_timeout: 600s
      - save_cache:
          key: deps-{{ .Branch }}
          paths:
            - local/perlbrew/perls
            - deps/pmtar

      - run:
          command: docker pull quay.io/wakaba/chromedriver:stable
          no_output_timeout: 600s
          background: true
      
      - run:
          command: make test-local-http-circle
          working_directory: /app
          no_output_timeout: 600s
      - run:
          command: make test-local-web-circle
          working_directory: /app
          environment:
            - WEBUA_DEBUG=1
            - TEST_WEBDRIVER_BROWSERS="chrome"
          no_output_timeout: 600s
