{
   "jobs" : {
      "test" : {
         "continue-on-error" : "${{ matrix.experimental }}",
         "env" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/test",
            "PMBP_PERL_VERSION" : "${{ matrix.perl_version }}"
         },
         "runs-on" : "ubuntu-latest",
         "steps" : [
            {
               "uses" : "actions/checkout@v2"
            },
            {
               "run" : "mkdir -p $CIRCLE_ARTIFACTS"
            },
            {
               "run" : "make test-deps"
            },
            {
               "run" : "make test"
            },
            {
               "uses" : "actions/upload-artifact@v3",
               "with" : {
                  "path" : "/tmp/circle-artifacts/test"
               }
            }
         ],
         "strategy" : {
            "fail-fast" : false,
            "matrix" : {
               "include" : [
                  {
                     "experimental" : false,
                     "perl_version" : "latest"
                  },
                  {
                     "experimental" : false,
                     "perl_version" : "5.14.2"
                  },
                  {
                     "experimental" : false,
                     "perl_version" : "5.8.9"
                  }
               ]
            }
         }
      }
   },
   "name" : "test",
   "on" : {
      "push" : {
      }
   }
}
